spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=bc8441579
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true